log_level: WARN
telemetry_disabled: true
storage:
  storage_path: ./data/qdrant/storage
  snapshots_path: ./data/qdrant/snapshots
service:
  host: 127.0.0.1
  http_port: 6333
  grpc_port: 6334
  enable_cors: false
  max_workers: 2
cluster:
  enabled: false

