import { expect, test } from '@playwright/test';
import { readFileSync, mkdirSync } from 'node:fs';

test('Login, dashboard and camera registration, editing and deletion', async ({ page }) => {
  const credentials = readFileSync('../data/local-admin.txt', 'utf8');
  const username = credentials.match(/^username: (.+)$/m)![1];
  const password = credentials.match(/^password: (.+)$/m)![1];
  const name = `E2E-${Date.now()}`;
  await page.goto('/');
  await expect(page.getByText('Server Connected')).toBeVisible();
  await page.getByLabel('Username', {exact:true}).fill(username);
  await page.getByLabel('Password', {exact:true}).fill(password);
  await page.getByRole('button', {name:'Log In',exact:true}).click();
  await expect(page.getByRole('heading', {name:'System Readiness'})).toBeVisible();
  const status = await (await page.request.get('/api/system/status')).json();
  expect(status.services.mariadb.status).toBe('ok');
  expect(status.services.qdrant.status).toBe('ok');
  await expect(page.getByRole('heading', {name:/Registered Cameras/})).toBeVisible();
  mkdirSync('../data/screenshots', {recursive:true});
  await page.screenshot({path:'../data/screenshots/dashboard.png',fullPage:true});
  await page.getByRole('navigation').getByRole('button', {name:/Cameras/}).click();
  await page.getByLabel('Camera Name', {exact:true}).fill(name);
  await page.getByLabel('Location', {exact:true}).fill('Test entrance');
  await page.getByLabel('RTSP Address', {exact:true}).fill('rtsp://e2e:private-credential@127.0.0.1:8554/live');
  await page.getByRole('button', {name:'Save Camera'}).click();
  let row = page.getByRole('row').filter({hasText:name});
  await expect(row).toBeVisible();
  await expect(row).not.toContainText('private-credential');
  await row.getByRole('button', {name:'Edit',exact:true}).click();
  await page.getByLabel('Camera Name', {exact:true}).fill(`${name}-Edit`);
  await page.getByLabel('RTSP Address', {exact:true}).fill('rtsp://e2e:private-credential@127.0.0.1:8554/live');
  await page.getByRole('button', {name:'Save Camera'}).click();
  row = page.getByRole('row').filter({hasText:`${name}-Edit`});
  await expect(row).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await row.getByRole('button', {name:'Delete',exact:true}).click();
  await expect(row).toHaveCount(0);
  await page.getByRole('button', {name:'Log Out'}).click();
  await expect(page.getByRole('heading', {name:'Log In',exact:true})).toBeVisible();
});
