import {expect, test} from '@playwright/test';
import {mkdirSync, readFileSync} from 'node:fs';

test('People, editor navigation, face comparison and deletion', async ({page, request}) => {
  test.setTimeout(90000);
  const credentials = readFileSync('../data/local-admin.txt', 'utf8');
  await page.goto('/');
  await page.getByLabel('Username', {exact:true}).fill(credentials.match(/^username: (.+)$/m)![1]);
  await page.getByLabel('Password', {exact:true}).fill(credentials.match(/^password: (.+)$/m)![1]);
  await page.getByRole('button', {name:'Log In', exact:true}).click();
  await expect(page.getByRole('heading', {name:'System Readiness'})).toBeVisible();
  const auth = await (await page.request.get('/api/auth/me')).json();
  const headers = {'X-CSRF-Token':auth.csrf_token};
  let personId: number | undefined;
  const name = `PERSON-E2E-${Date.now()}`;
  try {
    await page.getByRole('button', {name:/People/}).click();
    await expect(page.getByRole('heading', {name:'Search Targets', exact:true})).toBeVisible();
    await expect(page).toHaveURL(/#\/persons$/);
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.getByLabel('Person Name', {exact:true})).toHaveCount(0);
    await expect(page.getByRole('heading', {name:'Compare a Test Photo', exact:true})).toHaveCount(0);
    await page.getByRole('button', {name:'Add Person', exact:true}).click();
    const editor = page.locator('.person-editor');
    await expect(page).toHaveURL(/#\/persons\/new$/);
    await expect(page.getByRole('heading', {name:'Add Person', exact:true})).toBeVisible();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await editor.getByLabel('Person Name', {exact:true}).fill('Unsaved input');
    await page.getByRole('button', {name:'Back to List', exact:true}).click();
    await expect(editor).toHaveCount(0);
    await expect(page.getByRole('heading', {name:'Search Targets', exact:true})).toBeVisible();
    await page.getByRole('button', {name:'Add Person', exact:true}).click();
    await expect(editor.getByLabel('Person Name', {exact:true})).toHaveValue('');
    await expect(editor.getByLabel('Add Face Photos', {exact:false})).toBeEnabled();
    await editor.getByLabel('Person Name', {exact:true}).fill(name);
    const created = page.waitForResponse(response => response.url().endsWith('/api/persons') && response.request().method() === 'POST');
    await page.getByRole('button', {name:'Save Person', exact:true}).click();
    const result = await created;
    expect(result.status()).toBe(201);
    personId = (await result.json()).id;
    await expect(editor).toBeVisible();
    await expect(page.getByRole('heading', {name:'Edit Person', exact:true})).toBeVisible();
    await expect(page).toHaveURL(new RegExp(`#/persons/${personId}/edit$`));
    await expect(page.getByRole('heading', {name:`${name} · Reference Face`})).toBeVisible();
    await page.getByLabel('Add Face Photos', {exact:false}).setInputFiles(['../data/calibration/person_b_reference.jpg', '../data/calibration/person_b_variant.jpg']);
    await expect(page.getByRole('button', {name:'Save Cropped Face', exact:true})).toBeEnabled();
    await page.getByRole('button', {name:'Save Cropped Face', exact:true}).click();
    await expect(page.locator('.face-card')).toHaveCount(1);
    await expect(page.getByText('Cropped face saved. Select the region for the next image.')).toBeVisible();
    await expect(page.getByRole('button', {name:'Save Cropped Face', exact:true})).toBeEnabled();
    await page.getByRole('button', {name:'Save Cropped Face', exact:true}).click();
    await expect(page.getByText('Cropped face saved.', {exact:true})).toBeVisible({timeout:30000});
    await expect(page.locator('.face-card')).toHaveCount(2);
    await expect.poll(() => page.locator('.face-card img').first().evaluate((element: HTMLImageElement) => element.naturalWidth)).toBe(112);
    const person = await (await page.request.get(`/api/persons/${personId}`)).json();
    expect((await request.get(`/api/persons/${personId}/faces/${person.faces[0].id}/image`)).status()).toBe(401);
    await page.reload();
    await expect(page).toHaveURL(new RegExp(`#/persons/${personId}/edit$`));
    await expect(editor.getByLabel('Person Name', {exact:true})).toHaveValue(name);
    await expect(editor.locator('.face-card')).toHaveCount(2);
    await page.goBack();
    await expect(page.getByRole('heading', {name:'Search Targets', exact:true})).toBeVisible();
    await page.goForward();
    await expect(editor.getByLabel('Person Name', {exact:true})).toHaveValue(name);
    await expect(editor.locator('.face-card')).toHaveCount(2);
    let releaseSearch!: () => void;
    await page.route('**/api/persons/search', async route => {
      await new Promise<void>(resolve => {releaseSearch = resolve;});
      await route.continue();
    });
    await editor.getByLabel('Photo to Compare', {exact:true}).setInputFiles('../data/calibration/person_b_variant.jpg');
    await expect(page.getByRole('button', {name:'Back to List', exact:true})).toBeDisabled();
    await expect(page.getByRole('button', {name:/People/})).toBeDisabled();
    await page.keyboard.press('Escape');
    await expect(editor).toBeVisible();
    await expect.poll(() => Boolean(releaseSearch)).toBe(true);
    releaseSearch();
    const searchRow = editor.locator('.comparison-results').getByRole('row').filter({hasText:name});
    await expect(searchRow).toContainText('Similarity candidate', {timeout:15000});
    await page.unroute('**/api/persons/search');
    await page.getByLabel('Add Face Photos', {exact:false}).setInputFiles('../data/samples/zidane.jpg');
    await expect(page.getByRole('button', {name:'Save Cropped Face', exact:true})).toBeEnabled();
    await page.getByRole('button', {name:'Save Cropped Face', exact:true}).click();
    await expect(page.getByRole('alert')).toContainText('Multiple faces found');
    await expect(page.locator('.face-card')).toHaveCount(2);
    mkdirSync('../data/screenshots', {recursive:true});
    await page.screenshot({path:'../data/screenshots/phase4-person-page.png', fullPage:true});
    await page.getByRole('button', {name:'Back to List', exact:true}).click();
    await expect(editor).toHaveCount(0);
    const row = page.locator('.camera-list').getByRole('row').filter({hasText:name});
    await expect(row).toContainText('2 items');
    await row.getByRole('button', {name:'Edit', exact:true}).click();
    await expect(editor.getByLabel('Person Name', {exact:true})).toHaveValue(name);
    await expect(editor.locator('.face-card')).toHaveCount(2);
    await expect(editor.locator('.comparison-results')).toHaveCount(0);
    await expect(page.getByRole('alert')).toHaveCount(0);
    await page.getByLabel('Include in Search', {exact:true}).uncheck();
    const updated = page.waitForResponse(response => response.url().endsWith(`/api/persons/${personId}`) && response.request().method() === 'PUT');
    await page.getByRole('button', {name:'Save Person', exact:true}).click();
    expect((await updated).status()).toBe(200);
    await expect(editor).toBeVisible();
    await expect(editor.getByLabel('Include in Search', {exact:true})).not.toBeChecked();
    const disabledSearch = page.waitForResponse(response => response.url().endsWith('/api/persons/search') && response.request().method() === 'POST');
    await page.getByLabel('Photo to Compare', {exact:true}).setInputFiles('../data/calibration/person_b_reference.jpg');
    expect((await disabledSearch).status()).toBe(200);
    await expect(editor.locator('.comparison-results')).toBeVisible();
    await expect(searchRow).toHaveCount(0);
    page.once('dialog', dialog => dialog.accept());
    const faceRemoved = page.waitForResponse(response => response.url().includes(`/api/persons/${personId}/faces/`) && response.request().method() === 'DELETE');
    await page.getByRole('button', {name:'Delete Face', exact:true}).first().click();
    expect((await faceRemoved).status()).toBe(204);
    await expect(page.locator('.face-card')).toHaveCount(1);
    await page.setViewportSize({width:390, height:844});
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
    await expect(page.getByRole('button', {name:'Back to List', exact:true})).toBeVisible();
    await page.screenshot({path:'../data/screenshots/phase4-person-page-mobile.png', fullPage:true});
    await page.getByRole('button', {name:'Back to List', exact:true}).click();
    await page.setViewportSize({width:1280, height:720});
    await expect(row).toContainText('Exclude');
    await expect(row).toContainText('1 items');
    page.once('dialog', dialog => dialog.accept());
    const removed = page.waitForResponse(response => response.url().endsWith(`/api/persons/${personId}`) && response.request().method() === 'DELETE');
    await row.getByRole('button', {name:'Delete', exact:true}).click();
    expect((await removed).status()).toBe(204);
    await expect(row).toHaveCount(0);
    await page.goto(`/#/persons/${personId}/edit`);
    await expect(page.getByRole('alert')).toContainText('Person not found');
    await expect(page.getByLabel('Person Name', {exact:true})).toHaveCount(0);
    await page.getByRole('button', {name:'Back to List', exact:true}).click();
    personId = undefined;
  } finally {
    if (personId !== undefined) {
      const response = await page.request.delete(`/api/persons/${personId}`, {headers});
      expect([204,404]).toContain(response.status());
    }
    await page.request.post('/api/auth/logout', {headers});
  }
});
